// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebThermoThinApp.Data;

#nullable disable

namespace WebThermoThinApp.Migrations
{
    [DbContext(typeof(ThermoThinContext))]
    [Migration("20250604114600_AddCustomMaterialFieldsToVariant")]
    partial class AddCustomMaterialFieldsToVariant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WebThermoThinApp.Data.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CoolingTime")
                        .HasColumnType("REAL");

                    b.Property<double>("Emissivity")
                        .HasColumnType("REAL");

                    b.Property<double>("EnvTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("InitialTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaterialConductivity")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaterialDensity")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaterialHeatCapacity")
                        .HasColumnType("REAL");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
